### PR TITLE
feat: Ad insight reports

### PR DESCRIPTION
**Pull request by pnadolny13**
Closes https://github.com/MeltanoLabs/tap-facebook/issues/138

- Allows configurable insight streams
- Keep default stream but now we iterate properly to get each 1 day aggregated report until today/end_date config using async jobs like all other variants in the ecosystem
- Build streams dynamically using the facebook-business-sdk so we limit the amount of schemas and field lists we need to maintain over time
- handling edge cases related to lookback windows and how long facebook stores and refreshes data we're trying to extract

### CODE REVIEW

**Comment by edgarrmondragon** [comment]
I think it's caught in an infinite loop:

```
2024-01-30 01:07:30,628 | INFO     | tap-facebook.adsinsights_default | Sleeping for 5 seconds until job is done
2024-01-30 01:07:35,787 | INFO     | tap-facebook.adsinsights_default | Job Completed, 100% done
2024-01-30 01:07:36,429 | INFO     | tap-facebook.adsinsights_default | Job Not Started, 0% done
```

https://github.com/MeltanoLabs/tap-facebook/actions/runs/7704176621/job/20995993909?pr=151

**Comment by pnadolny13** [comment]
@edgarrmondragon oh yeah looks like it was trying to backfill data all the way back 3 years. I'll update it to log the date range so its more obvious and see if I can limit the date range for this stream.

**Comment by pnadolny13** [comment]
@edgarrmondragon this should be good now. I added a proper start date to the CI tests and fixed all the linting issues.

**Comment by edgarrmondragon** [comment]
@pnadolny13 #152

**Review by edgarrmondragon — APPROVED** [review]

**Pull request merged**
