### PR TITLE
fix: Exclude deprecated insights fields for v19.0 and above

### PR DESCRIPTION
**Pull request by spencerjbeckwith**
Some insights fields were deprecated in [API Version 19](https://developers.facebook.com/docs/marketing-api/marketing-api-changelog/version19.0/). Running the tap gave me this error:

```
  Status:  400
  Response:
    {
      "error": {
        "message": "(#100) age_targeting, gender_targeting, labels, location, estimated_ad_recall_rate_lower_bound, estimated_ad_recall_rate_upper_bound, estimated_ad_recallers_lower_bound, estimated_ad_recallers_upper_bound are not valid for fields param after V19.0",
        "type": "OAuthException",
        "code": 100,
        "fbtrace_id": "****"
      }
    }
```

By adding these fields to the `EXCLUDED_FIELDS` list I no longer received the error and the tap could complete successfully.

In order to prevent somehow breaking previous integrations, it may be worthwhile to check these specific fields against the configured `api_version`. I figured that would be overkill to resolve the error, but I'd be happy to contribute that if needed.

### CODE REVIEW

**Comment by edgarrmondragon** [comment]
Should we also update the default version to v19.0 in `tap.py`?

**Comment by guillaumemeyer** [comment]
@spencerjbeckwith I was facing this issue and manually patched ad_insights.py with the suggested fields exclusion and it works.
This merge is definitely needed.

@edgarrmondragon v19 looks like a good new default version

**Comment by edgarrmondragon** [comment]
Superseded by https://github.com/MeltanoLabs/tap-facebook/pull/262

**Comment by edgarrmondragon** [comment]
Thanks @spencerjbeckwith!

**Pull request closed without merging**
